exports.stackStatusFilter = [
    "CREATE_COMPLETE", "CREATE_FAILED", "CREATE_IN_PROGRESS",
    "DELETE_FAILED", "DELETE_IN_PROGRESS", "ROLLBACK_COMPLETE",
    "ROLLBACK_FAILED", "ROLLBACK_IN_PROGRESS", "UPDATE_COMPLETE",
    "UPDATE_FAILED", "UPDATE_IN_PROGRESS", "UPDATE_ROLLBACK_COMPLETE",
    "UPDATE_COMPLETE_CLEANUP_IN_PROGRESS", "UPDATE_ROLLBACK_FAILED", 
    "UPDATE_ROLLBACK_IN_PROGRESS", "UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS"
];